fix: local vip on newer versions
UnblockNeteaseMusic/server pull request #1046
Opened 2023-04-08 15:21 UTC by Creepercdn

Fix #926

2023-04-08 15:26 UTC, Creepercdn commented on src/hook.js
> +						nVipLevel = 5; // ? months
不知道这个要怎么处理比较好...

2023-04-08 15:32 UTC, pan93412 requested changes

2023-04-08 15:32 UTC, pan93412 commented on src/hook.js
> +								}
这个片段好像一直重复，有考虑写一个变量保存这个结构，需要的时候再拷贝吗？

```js
const defaultPackage = {
  iconUrl: null,
  dynamicIconUrl: null,
  isSign: false // ...
};

if (!info.data.musicPackage) {
  info.data.musicPackage = {...defaultPackage};
}
```

2023-04-08 15:32 UTC, pan93412 commented on src/hook.js
> +								if (ENABLE_LOCAL_VIP){
有些判断可以提前返回，可以避免像现在这样太深的巢套：

```
if (!ENABLE_LOCAL_VIP) return;

if (!info.data.redplus) {
  ...
}
```

2023-04-08 15:32 UTC, pan93412 commented on src/hook.js
> +								info.data.associator.vipLevel = nVipLevel;
有个比较简洁的写法：

```js
info.data.associator = {
  ...defaultPackage, // 预设值
  ...info.data.associator, // 输入的值
  vipCode: 100,  // 你要更改的值
  vipLevel: nVipLevel,
};
```

这样子就可以省掉一次 `if (!info.data.associator)` 的判断了。

附一些 spread operator 的一些使用范例：

```js
> const i = { aaa: 1 }
undefined
> const j = null;
undefined
> { ...i, ...j, aaa: 2 }
{ aaa: 2 }
> { ...i, ...j, bbb: 2 }
{ aaa: 1, bbb: 2 }
> const k = { aaa: 23456 }
undefined
> { ...i, ...k, bbb: 2 }
{ aaa: 23456, bbb: 2 }
```

2023-04-08 15:35 UTC, pan93412 commented on src/hook.js
> +						nVipLevel = 5; // ? months
如果目前可以运作的话，就先这样吧

2023-04-08 15:42 UTC, Creepercdn commented on src/hook.js
> +								if (ENABLE_LOCAL_VIP){
这里 return 会把整个函数结束掉，然而后面还有代码需要执行

2023-04-08 15:43 UTC, pan93412 commented on src/hook.js
> +								if (ENABLE_LOCAL_VIP){
> 这里 return 会把整个函数结束掉，然而后面还有代码需要执行

舉例而已啦（

另外你也可能需要重新排序一下程式碼

2023-04-08 16:07 UTC, pan93412 requested changes
另外建议跑个 `prettier` 重新格式化一下，可以少掉之后的一次 prettier PR。

2023-04-08 16:07 UTC, pan93412 commented on src/hook.js
> +						if (info && (LOCAL_VIP_UID==NaN || (info.data.userId === LOCAL_VIP_UID))) {
`NaN` 始终不等于 `NaN`，所以你这条件可能永远都进不去：

```
> NaN == NaN
false
```

可以用 `Number.isNaN` 检查是不是 `NaN`：

```
> Number.isNaN(1234)
false
> Number.isNaN(NaN)
true
```

2023-04-08 16:07 UTC, pan93412 commented on src/hook.js
> +						var info =
因为你没有要变动 `info` 本身（而是只修改里面的 member），故这里的 info 可以用 `const` 就好。

2023-04-09 05:30 UTC, pan93412 approved these changes

2023-04-09 09:07 UTC, 1715173329 commented on README.md
> +| ENABLE_LOCAL_SVIP     | bool | 激活本地黑胶 SVIP（开启 ENABLE_LOCAL_VIP 时；默认为 CVIP）                                              | `ENABLE_LOCAL_SVIP=true`                                         |
有特别单独做个 option 的必要吗？感觉也可以直接用 ENABLE_LOCAL_VIP。

2023-04-09 09:07 UTC, 1715173329 commented on README.md
> +| LOCAL_VIP_UID         | int  | 仅对此 UID 激活本地黑胶 VIP，默认为对全部用户生效                                                       | `LOCAL_VIP_UID=123456789`                                        |
可以是一个用英文分号之类分隔的 array，允许设置多个 uid

2023-04-09 12:14 UTC, Creepercdn commented on README.md
> +| ENABLE_LOCAL_SVIP     | bool | 激活本地黑胶 SVIP（开启 ENABLE_LOCAL_VIP 时；默认为 CVIP）                                              | `ENABLE_LOCAL_SVIP=true`                                         |
感觉可能会有兼容性的问题。那就把 ENABLE_LOCAL_VIP 改为 str，可选值为 `true`，`cvip` 和 `svip`。

2023-04-09 12:27 UTC, 1715173329 commented on README.md
> +| ENABLE_LOCAL_SVIP     | bool | 激活本地黑胶 SVIP（开启 ENABLE_LOCAL_VIP 时；默认为 CVIP）                                              | `ENABLE_LOCAL_SVIP=true`                                         |
应该不会，我在 pc 2.2.0 版本上面测了下没什么问题，也只是扩展了一下字段而已。

2023-04-09 12:48 UTC, 1715173329 approved these changes
lgtm, thanks

2023-04-09 12:59 UTC, pan93412 approved these changes

2023-04-09 12:59 UTC, merged