feat(provider/migu): migrate to new API
UnblockNeteaseMusic/server pull request #639
Opened 2022-04-13 17:29 UTC by 1715173329

2022-04-13 23:09 UTC, pan93412 requested changes

2022-04-13 23:09 UTC, pan93412 commented on src/provider/migu.js
> +			song.url.split('/').slice(3).join('/')
這裡可讀性不太好

2022-04-15 23:45 UTC, 1715173329 commented
Any idea?

2022-04-18 12:47 UTC, pan93412 approved these changes

2022-04-18 18:56 UTC, merged