针对Windows服务模块添加env配置项
UnblockNeteaseMusic/server pull request #876
Opened 2022-10-04 07:10 UTC by whosydd

2022-10-07 16:17 UTC, 1715173329 requested changes

2022-10-07 16:17 UTC, 1715173329 commented on nw.js
> +	env: [
如果支持直接配置，引入 .env 的具体意义是什么？

2022-10-07 16:17 UTC, 1715173329 commented on nw.js
> -	// scriptOptions:'-p 52100:52101', // 可选参数示例: 自定义端口并开启HTTPS
请保留本示例，您的 commit title 中也未曾提到过此更改。

2022-10-07 16:17 UTC, 1715173329 commented on README.md
> +关于环境变量的配置，请在项目根目录创建`.env`文件，并在其中配置相关选项，具体格式请参考<a href="#环境变量">环境变量</a>
请参见[中文排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)，添加对应的空格，QQ 应为大写字符。

2022-10-07 17:41 UTC, whosydd commented on nw.js
> +	env: [
哎呀！这里我惯性思维了，用 `.env` 习惯了。。。

2022-10-08 05:20 UTC, 1715173329 approved these changes
LGTM - Thanks!

2022-10-08 05:21 UTC, merged