feat(provider/find): add album name to search keywords
UnblockNeteaseMusic/server pull request #961
Opened 2022-12-23 11:16 UTC by luoxiaohei

**主要变化**

在关键字中添加了专辑名称。

**改动目的** 

在歌曲有较多版本时能够更精确的匹配到歌曲。

**当前问题**

举一个 QQ 音乐的 bad case

在 QQ 音源中，关键词 `东北民谣 (Live) - 毛不易` 默认返回的是合唱吧的版本，并且折叠了我是唱作人的歌曲版本

<img width="803" alt="image" src="https://user-images.githubusercontent.com/7138906/209323562-8426ac45-f36e-4113-9f62-edea1fd5135b.png">

在 API 的响应中也没有我是唱作人版本的歌曲信息

```json
[
      {
        "id": "75945187",
        "name": "东北民谣",
        "duration": 243000,
        "album": {
          "id": "10632126",
          "name": "合唱吧！300&nbsp;第6期"
        },
        "artists": [
          {
            "id": 1456705,
            "name": "毛不易"
          }
        ]
      },
      {
        "id": "186102653",
        "name": "东北民谣",
        "duration": 59000,
        "album": {
          "id": "0",
          "name": ""
        },
        "artists": [
          {
            "id": 1456705,
            "name": "毛不易"
          }
        ]
      },
      ...
    ]
```
展开后才能看到我是唱作人的版本

<img width="795" alt="image" src="https://user-images.githubusercontent.com/7138906/209324850-03bc034d-92b3-4539-91c9-fb16660e4901.png">

这导致在播放这首歌的我是唱作人版本时，由于没有完全一致的结果，最终选择了错误结果（目前是选择了小沈阳的跨界歌王版本）。

在关键词中加入专辑名称后，就能够返回更匹配的结果

<img width="795" alt="image" src="https://user-images.githubusercontent.com/7138906/209326232-8daa610b-b8fa-4522-a87d-0dce78149ab5.png">

2022-12-23 11:21 UTC, pan93412 requested changes

2022-12-23 11:21 UTC, pan93412 commented on src/provider/find.js
> +			info.album.name;
建議寫一個 `info.album?.name ?? ""` 防止出現 `undefined` 的情況。

2022-12-23 11:25 UTC, luoxiaohei commented on src/provider/find.js
> +			info.album.name;
赞，我加一下

2022-12-23 11:25 UTC, luoxiaohei commented on src/provider/find.js
> +			info.album.name;
> 建議寫一個 `info.album?.name ?? ""` 防止出現 `undefined` 的情況。

👍🏻，我加一下

2022-12-23 11:31 UTC, luoxiaohei commented on src/provider/find.js
> +			info.album.name;
已经加好了哈

2022-12-23 11:35 UTC, pan93412 commented on src/provider/find.js
> +			info.album?.name ?? '';
你有考慮 `.trim()` 一下嗎（考慮到 `album.name` 是空白的情況）

    info.keyword = (...).trim()

我不知道空白會不會影響搜尋結果，不會影響不 `trim()` 也可以

2022-12-23 11:42 UTC, luoxiaohei commented on src/provider/find.js
> +			info.album?.name ?? '';
我不太确定是否会影响，保险起见还是加一下，我看 QQ 音乐好像是在前端 trim 掉了

辛苦帮忙看看最新的提交写对不对哈，我对 js 不太熟悉，给你添麻烦了

2022-12-23 12:37 UTC, pan93412 approved these changes
r? @1715173329

2022-12-23 12:37 UTC, luoxiaohei commented
更新：检查专辑名与歌曲名是否相同，如果一样就不加专辑名了

badcase: QQ 音乐 `甘心替代你 - 毛不易 甘心替代你` 增加专辑名后未能匹配最优结果

2022-12-23 17:08 UTC, 1715173329 commented
> r? @1715173329

我不好说，它可能无法在所有音源下正常工作。
另外，同一首歌也会在不同专辑下分发，附上专辑名称可能会导致匹配不到歌曲（经常用网易云的话应该对这种情况很熟悉）。

2022-12-24 04:29 UTC, luoxiaohei commented
> > r? @1715173329
> 
> 我不好说，它可能无法在所有音源下正常工作。
> 另外，同一首歌也会在不同专辑下分发，部分专辑有版权部分专辑没有，附上专辑名称可能会导致匹配不到歌曲（经常用网易云的话应该对这种情况很熟悉）。

目前有哪些音源是精确匹配么？如果模糊匹配的话应该不会有匹配不到的情况，但是确实对于匹配度可能会有影响。我目前看到的还是正面影响更多一些，但是我个人的样本量比较小，不一定准确。

或者我们可以把它作为一个选项？或者把关键词的模板暴露出来允许自定义之类的，以满足不同类型用户的需求？

2022-12-24 04:57 UTC, 1715173329 commented
> 目前有哪些音源是精确匹配么？如果模糊匹配的话应该不会有匹配不到的情况，但是确实对于匹配度可能会有影响。我目前看到的还是正面影响更多一些，但是我个人的样本量比较小，不一定准确。

热门歌曲这样做是没有大问题的，但是也需要考虑到冷门歌曲，每个平台之间的音乐信息就会出现偏差了。比如酷我或者咪咕，附加专辑名称之后就匹配不到正确的歌曲了。

> 或者我们可以把它作为一个选项？或者把关键词的模板暴露出来允许自定义之类的，以满足不同类型用户的需求？

作为选项是可以的。做模板的话会加大复杂度了，我不好说。

2022-12-24 05:51 UTC, luoxiaohei commented
> > 目前有哪些音源是精确匹配么？如果模糊匹配的话应该不会有匹配不到的情况，但是确实对于匹配度可能会有影响。我目前看到的还是正面影响更多一些，但是我个人的样本量比较小，不一定准确。
> 
> 热门歌曲这样做是没有大问题的，但是也需要考虑到冷门歌曲，每个平台之间的音乐信息就会出现偏差了。比如酷我或者咪咕，附加专辑名称之后就匹配不到正确的歌曲了。
> 
> > 或者我们可以把它作为一个选项？或者把关键词的模板暴露出来允许自定义之类的，以满足不同类型用户的需求？
> 
> 作为选项是可以的。做模板的话会加大复杂度了，我不好说。

嗯嗯，我先加个选项进来，可能要晚一些，人在外边。

2022-12-26 06:45 UTC, luoxiaohei commented
已经通过环境变量的方式添加了功能选项，@pan93412 @1715173329 再帮忙看下？

2022-12-26 06:53 UTC, pan93412 approved these changes

2022-12-26 07:03 UTC, 1715173329 approved these changes
Thanks.

2022-12-27 03:50 UTC, merged